version: '3.9'
services:

  mariadb:
    image: registry.gitlab.iitsp.com/allworldit/docker/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - MYSQL_DATABASE=testdb

  powerdns:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      - POWERDNS_SERVER_ID=test.server
      - POWERDNS_WEBSERVER_ALLOW_FROM=0.0.0.0/0
      - MYSQL_HOST=mariadb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - MYSQL_DATABASE=testdb
    depends_on:
      - mariadb
    ports:
      - 8081:8081
      - 8053:8053/TCP
      - 8053:8053/UDP

